### PR TITLE
added support for ASCII smileys

### PR DESCRIPTION
**Pull request by sjsakib**
Hello,
I've added option to enable  ASCII smileys. Default stays false.

I've also updated the doc.

### CODE REVIEW

**Comment by sjsakib** [comment]
@Rulikkk Can you merge it bro?

**Comment by Rulikkk** [comment]
@sjsakib done!
_Note: this doesn't push to npm_, I will do it later.

**Comment by Rulikkk** [comment]
@sjsakib I've just published this to npm

**Comment by sjsakib** [comment]
@Rulikkk Great :+1:

**Pull request merged**
